config/routes.rb
Speiseplan::Application.routes.draw do
  get "welcome/index"
  root to: 'welcome#index'

  resources :ingredients
  resources :quantities
  resources :recipes

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, 
  	:ingredient_id

  has_many :quantities
  has_many :recipes, through: :quantities
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  attr_accessible :amount, 
  	:ingredient_id,
  	:ingredient_attributes

  belongs_to :recipe
  belongs_to :ingredient

  accepts_nested_attributes_for :ingredient,
  	:reject_if => :all_blank
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :description, 
  	:instructions, 
  	:title, 
  	:quantities_attributes, 
  	:ingredients_attributes

  has_many :quantities
  has_many :ingredients, :through => :quantities

  accepts_nested_attributes_for :quantities,
  	:reject_if => :all_blank,
  	:allow_destroy => true
  accepts_nested_attributes_for :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index

    gon.ingredients = Ingredient.limit(10)

    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController
  # GET /quantities
  # GET /quantities.json
  def index
    @quantities = Quantity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quantities }
    end
  end

  # GET /quantities/1
  # GET /quantities/1.json
  def show
    @quantity = Quantity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quantity }
    end
  end

  # GET /quantities/new
  # GET /quantities/new.json
  def new
    @quantity = Quantity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quantity }
    end
  end

  # GET /quantities/1/edit
  def edit
    @quantity = Quantity.find(params[:id])
  end

  # POST /quantities
  # POST /quantities.json
  def create
    @quantity = Quantity.new(params[:quantity])

    respond_to do |format|
      if @quantity.save
        format.html { redirect_to @quantity, notice: 'Quantity was successfully created.' }
        format.json { render json: @quantity, status: :created, location: @quantity }
      else
        format.html { render action: "new" }
        format.json { render json: @quantity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quantities/1
  # PUT /quantities/1.json
  def update
    @quantity = Quantity.find(params[:id])

    respond_to do |format|
      if @quantity.update_attributes(params[:quantity])
        format.html { redirect_to @quantity, notice: 'Quantity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quantity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quantities/1
  # DELETE /quantities/1.json
  def destroy
    @quantity = Quantity.find(params[:id])
    @quantity.destroy

    respond_to do |format|
      format.html { redirect_to quantities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index

    gon.recipes = Recipe.all

    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ingredients/_form.html.erb
<%= simple_form_for(@ingredient) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<div id="ingredients" data-ingredients="<%= render(template: "ingredients/index.json.rabl")%>">
  
</div>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.name %></td>
    <td><%= link_to 'Show', ingredient %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ingredient.name %>
</p>

<p>
  <b>ID:</b>
  <%= @ingredient.id %>
</p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Speiseplan</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "ui-lightness/jquery-ui-1.10.3.custom.css" %>
  <%= javascript_include_tag "application", "jquery-ui-1.10.3.custom.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<h1><%= link_to 'Speiseplan', recipes_path %></h1>
	<%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Speiseplan
		= include_gon
		= stylesheet_link_tag "application"
		= stylesheet_link_tag "ui-lightness/jquery-ui-1.10.3.custom.css"
		= javascript_include_tag "application", "jquery-ui-1.10.3.custom.js"
		= csrf_meta_tags
	%body
		.container
			%h1 
				=link_to 'Speiseplan', root_path
			= yield

/ <!DOCTYPE html>
/ <html>
/ <head>
/   <title>Speiseplan</title>
/   <%= include_gon %>
/   <%= stylesheet_link_tag    "application", :media => "all" %>
/   <%= stylesheet_link_tag    "ui-lightness/jquery-ui-1.10.3.custom.css" %>
/   <%= javascript_include_tag "application", "jquery-ui-1.10.3.custom.js" %>
/   <%= csrf_meta_tags %>
/ </head>
/ <body>

/ <div class="container">
/ 	<h1><%= link_to 'Speiseplan', root_path %></h1>
/ 	<%= yield %>
/ </div>

/ </body>
/ </html>

app/views/quantities/_form.html.erb
<%= simple_form_for(@quantity) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :amount %>
    <%= f.input :ingredient_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/quantities/edit.html.erb
<h1>Editing quantity</h1>

<%= render 'form' %>

<%= link_to 'Show', @quantity %> |
<%= link_to 'Back', quantities_path %>

app/views/quantities/index.html.erb
<h1>Listing quantities</h1>

<table>
  <tr>
    <th>Amount</th>
    <th>Ingredient</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quantities.each do |quantity| %>
  <tr>
    <td><%= quantity.amount %></td>
    <td><%= quantity.ingredient_id %></td>
    <td><%= link_to 'Show', quantity %></td>
    <td><%= link_to 'Edit', edit_quantity_path(quantity) %></td>
    <td><%= link_to 'Destroy', quantity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quantity', new_quantity_path %>

app/views/quantities/new.html.erb
<h1>New quantity</h1>

<%= render 'form' %>

<%= link_to 'Back', quantities_path %>

app/views/quantities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @quantity.amount %>
</p>

<p>
  <b>Ingredient:</b>
  <%= @quantity.ingredient_id %>
</p>


<%= link_to 'Edit', edit_quantity_path(@quantity) %> |
<%= link_to 'Back', quantities_path %>

app/views/recipes/_form.html.haml
.row
	.span4
		%h3 Ingredients
		= simple_form_for @recipe do |f|
			= f.simple_fields_for :quantities do |q|
				= render 'quantity_fields', :f => q
			= link_to_add_association 'add ingredient', f, :quantities
	.span8
		%h3 Recipe
		= simple_form_for @recipe do |f|
			= f.input :title
			= f.input :description
			= f.input :instructions
			= f.submit

app/views/recipes/_ingredient_fields.html.haml
.new-ingredient
	= f.input :name, input_html: { class: 'ingredient-input' }

app/views/recipes/_quantity_fields.html.haml
.nested-fields
	= f.input :amount
	= f.association :ingredient, :collection => Ingredient.all(:order => 'name'), :prompt => 'Choose an existing ingredient'
	= link_to_remove_association "remove ingredient", f
	%br
	= link_to_add_association 'or create a new ingredient', f, :ingredient, :render_options => {:wrapper => 'bootstrap' }

app/views/recipes/edit.html.erb
<h2>Editing <%= @recipe.title %></h2>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h2>Rezepte Überblick</h2>

<table>
  <tr>
    <th>Title</th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.title %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h2>Rezept eingeben</h2>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @recipe.title %>
</p>

<p>
  <b>Description:</b>
  <%= @recipe.description %>
</p>

<p>
  <b>Ingredients:</b>
  <% @recipe.quantities.each do |q| %>
  	<li><%= q.amount %> <%= q.ingredient.name %></li>
  <% end %>
</p>

<p>
  <b>Instructions:</b>
  <%= @recipe.instructions %>
</p>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.haml
/ <p id="notice"><%= notice %></p>

%h2= @recipe.title
.row
  .span4
    %h3 Zutaten
    %ul
      - @recipe.quantities.each do |q|
        %li.ingredient
          = q.amount
          = q.ingredient.name
    %h4 Menüart
    %p= @recipe.description
  .span8
    %h3 Zubereitung
    %p= @recipe.instructions
    = link_to 'Edit', edit_recipe_path(@recipe)
    = link_to 'Back', recipes_path

app/views/welcome/index.html.haml
%h2 Welcome
= link_to 'Recipes', recipes_path